source 'https://rubygems.org'

gem 'fluentd', '~>0.12.32'
gem 'activesupport', '~>4.2.6'
gem 'fluent-plugin-kubernetes_metadata_filter', '~>0.27.0'
gem 'fluent-plugin-elasticsearch', '~>1.9.5'
gem 'fluent-plugin-systemd', '~>0.0.8'
gem 'fluent-plugin-prometheus', '~>0.3.0'
gem 'fluent-plugin-multi-format-parser', '~>0.1.1'
gem 'oj', '~>2.18.1'
gem 'fluent-plugin-record-modifier'
gem 'fluent-plugin-exclude-filter'
gem 'systemd-journal'
gem 'fluent-plugin-rewrite-tag-filter'
gem 'fluent-plugin-filter'
gem 'fluent-plugin-remote_syslog'
gem 'fluent-plugin-kubernetes_remote_syslog'
